---
title: "simpleRegress"
author: "Ezra Licciardi"
date: "Fall 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
bears <- read.csv(file="BEARS.csv",header = TRUE)
#adjust factors to be factors
bears$SEX<- as.factor(bears$SEX)
bears$MONTH<- as.factor(bears$MONTH)
```

# Models in Order of Fitness

## First
```{r}
HeadLen <- lm(LENGTH~HEADLEN,data=bears)
plot(LENGTH~HEADLEN,data=bears)
abline(HeadLen)
summary.lm(HeadLen)
```
Adjusted R Squared - 0.8434
Residual Standard Error - 4.235

## Second
```{r}
Chest <- lm(LENGTH~CHEST,data=bears)
plot(LENGTH~CHEST,data=bears)
abline(Chest)
summary.lm(Chest)
```
Adjusted R Squared - 0.7869
Residual Standard Error - 4.939

## Third
```{r}
Neck <- lm(LENGTH~NECK,data=bears)
plot(LENGTH~NECK,data=bears)
abline(Neck)
summary.lm(Neck)
```
Adjusted R Squared - 0.7476
Residual Standard Error - 5.376

## Fourth
```{r}
Weight <- lm(LENGTH~WEIGHT,data=bears)
plot(LENGTH~WEIGHT,data=bears)
abline(Weight)
summary.lm(Weight)
```
Adjusted R Squared - 0.7423
Residual Standard Error - 5.432

## Fifth
```{r}
HeadWth <- lm(LENGTH~HEADWTH,data=bears)
plot(LENGTH~HEADWTH,data=bears)
abline(HeadWth)
summary.lm(HeadWth)
```
Adjusted R Squared - 0.5321
Residual Standard Error - 7.23
